// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/db/favorite/schema/favorite.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2365810819321998575),
    name: 'Favorite',
    lastPropertyId: const obx_int.IdUid(6, 6162810112563861626),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7635873026558841224),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3030372273365204535),
        name: 'imageId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4657482334892715789),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7510230980041264374),
        name: 'urlHeight',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1736526418466199975),
        name: 'urlWidth',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8754304991187197504),
        name: 'breedName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6162810112563861626),
        name: 'url',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2365810819321998575),
    lastIndexId: const obx_int.IdUid(1, 4657482334892715789),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Favorite: obx_int.EntityDefinition<Favorite>(
      model: _entities[0],
      toOneRelations: (Favorite object) => [],
      toManyRelations: (Favorite object) => {},
      getId: (Favorite object) => object.id,
      setId: (Favorite object, int id) {
        object.id = id;
      },
      objectToFB: (Favorite object, fb.Builder fbb) {
        final imageIdOffset = fbb.writeString(object.imageId);
        final breedNameOffset = fbb.writeString(object.breedName);
        final urlOffset = fbb.writeString(object.url);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, imageIdOffset);
        fbb.addInt64(2, object.urlHeight);
        fbb.addInt64(3, object.urlWidth);
        fbb.addOffset(4, breedNameOffset);
        fbb.addOffset(5, urlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final imageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final urlHeightParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final urlWidthParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final breedNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Favorite(
          imageId: imageIdParam,
          url: urlParam,
          urlHeight: urlHeightParam,
          urlWidth: urlWidthParam,
          breedName: breedNameParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Favorite] entity fields to define ObjectBox queries.
class Favorite_ {
  /// See [Favorite.id].
  static final id = obx.QueryIntegerProperty<Favorite>(
    _entities[0].properties[0],
  );

  /// See [Favorite.imageId].
  static final imageId = obx.QueryStringProperty<Favorite>(
    _entities[0].properties[1],
  );

  /// See [Favorite.urlHeight].
  static final urlHeight = obx.QueryIntegerProperty<Favorite>(
    _entities[0].properties[2],
  );

  /// See [Favorite.urlWidth].
  static final urlWidth = obx.QueryIntegerProperty<Favorite>(
    _entities[0].properties[3],
  );

  /// See [Favorite.breedName].
  static final breedName = obx.QueryStringProperty<Favorite>(
    _entities[0].properties[4],
  );

  /// See [Favorite.url].
  static final url = obx.QueryStringProperty<Favorite>(
    _entities[0].properties[5],
  );
}
